import os

def create_header():
    header_path = 'src/network/html_content.h'
    files = {
        'index.html': 'INDEX_HTML',
        'app.js': 'APP_JS',
        'style.css': 'STYLE_CSS'
    }
    
    with open(header_path, 'w', encoding='utf-8') as f:
        f.write('#pragma once\n\n')
        f.write('// Autogenerated from data/ directory\n\n')
        
        for file_name, var_name in files.items():
            path = os.path.join('data', file_name)
            if os.path.exists(path):
                with open(path, 'r', encoding='utf-8') as src:
                    content = src.read()
                f.write(f'const char {var_name}[] PROGMEM = R"rawliteral(\n')
                f.write(content)
                f.write('\n)rawliteral";\n\n')
                print(f'Embedded {file_name} into {var_name}')

if __name__ == "__main__":
    create_header()
