$files = @{
    "index.html" = "INDEX_HTML"
    "app.js" = "APP_JS"
    "style.css" = "STYLE_CSS"
}

$outPath = "src\network\html_content.h"

Set-Content -Path $outPath -Value "#pragma once`r`n`r`n// Autogenerated from data/ directory`r`n`r`n" -Encoding UTF8

foreach ($key in $files.Keys) {
    $varName = $files[$key]
    $filePath = "data\$key"
    if (Test-Path $filePath) {
        $content = Get-Content -Path $filePath -Raw -Encoding UTF8
        $block = "const char $varName`[] PROGMEM = R`"rawliteral(`n$content`n)rawliteral`";`r`n`r`n"
        Add-Content -Path $outPath -Value $block -Encoding UTF8
        Write-Host "Embedded $key into $varName"
    }
}
