#pragma once

// Autogenerated from data/ directory


const char APP_JS[] PROGMEM = R"rawliteral(
const state = {
    theme: localStorage.getItem('theme') || 'dark',
    history: [],
    limits: { min: 6.0, max: 8.0 },
    chartData: null
};

// Elements
const el = {
    themeToggle: document.getElementById('theme-toggle'),
    iconLight: document.getElementById('theme-icon-light'),
    iconDark: document.getElementById('theme-icon-dark'),
    statusDot: document.getElementById('status-dot'),
    statusText: document.getElementById('status-text'),
    lastUpdate: document.getElementById('last-update'),
    fwVersion: document.getElementById('fw-version')
};

// Initialize Theme
function initTheme() {
    document.documentElement.setAttribute('data-theme', state.theme);
    updateThemeIcon();
}

function toggleTheme() {
    state.theme = state.theme === 'dark' ? 'light' : 'dark';
    document.documentElement.setAttribute('data-theme', state.theme);
    localStorage.setItem('theme', state.theme);
    updateThemeIcon();
    drawChart();
}

function updateThemeIcon() {
    if (state.theme === 'dark') {
        el.iconLight.style.display = 'block';
        el.iconDark.style.display = 'none';
    } else {
        el.iconLight.style.display = 'none';
        el.iconDark.style.display = 'block';
    }
}

el.themeToggle.addEventListener('click', toggleTheme);
initTheme();

// Helpers
function formatTime(seconds) {
    const d = Math.floor(seconds / (3600*24));
    const h = Math.floor((seconds % (3600*24)) / 3600);
    const m = Math.floor((seconds % 3600) / 60);
    const s = Math.floor(seconds % 60);
    
    if (d > 0) return `${d}d ${h}h ${m}m`;
    return `${h.toString().padStart(2, '0')}:${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')}`;
}

function phColor(ph) {
    if (ph < state.limits.min) return '#f87171'; // Acid / Red
    if (ph > state.limits.max) return '#60a5fa'; // Base / Blue
    return '#4ade80'; // Neutral / Green
}

function setPhColor(element, ph) {
    element.style.color = phColor(ph);
}

// Chart
function drawChart() {
    if (!state.chartData || state.chartData.length === 0) return;
    
    const canvas = document.getElementById('phChart');
    if (!canvas) return;
    
    const ctx = canvas.getContext('2d');
    const dpr = window.devicePixelRatio || 1;
    const rect = canvas.parentNode.getBoundingClientRect();
    
    canvas.width = rect.width * dpr;
    canvas.height = (rect.height || 220) * dpr;
    
    ctx.scale(dpr, dpr);
    canvas.style.width = `${rect.width}px`;
    canvas.style.height = `${rect.height || 220}px`;
    
    const width = rect.width;
    const height = rect.height || 220;
    
    ctx.clearRect(0, 0, width, height);
    
    const root = getComputedStyle(document.documentElement);
    const textColor = root.getPropertyValue('--text-muted').trim() || '#718096';
    const gridColor = root.getPropertyValue('--border-card').trim() || '#2d3748';
    
    const padding = { top: 20, right: 20, bottom: 30, left: 40 };
    const chartW = width - padding.left - padding.right;
    const chartH = height - padding.top - padding.bottom;
    
    const phValues = state.chartData.map(d => (d.p !== undefined ? d.p : d.ph));
    const phMin = Math.max(0, Math.min(...phValues, state.limits.min) - 0.5);
    const phMax = Math.min(14, Math.max(...phValues, state.limits.max) + 0.5);
    
    const mapX = (i) => padding.left + (i / Math.max(1, state.chartData.length - 1)) * chartW;
    const mapY = (ph) => padding.top + chartH - ((ph - phMin) / Math.max(0.1, phMax - phMin)) * chartH;
    
    // Draw Grid
    ctx.font = '11px Inter, sans-serif';
    ctx.fillStyle = textColor;
    ctx.textAlign = 'right';
    ctx.textBaseline = 'middle';
    
    const gridLines = [0, 2, 4, 6, 7, 8, 10, 12, 14].filter(v => v >= phMin && v <= phMax);
    
    ctx.lineWidth = 1;
    gridLines.forEach(val => {
        const y = mapY(val);
        ctx.beginPath();
        ctx.strokeStyle = val === 7 ? '#4a5568' : gridColor;
        if(val === 7) ctx.setLineDash([4, 4]); else ctx.setLineDash([]);
        ctx.moveTo(padding.left, y);
        ctx.lineTo(width - padding.right, y);
        ctx.stroke();
        ctx.fillText(val.toFixed(1), padding.left - 8, y);
    });
    ctx.setLineDash([]);
    
    // Draw Alarm Limits
    if (state.limits.min >= phMin && state.limits.min <= phMax) {
        const y = mapY(state.limits.min);
        ctx.beginPath();
        ctx.strokeStyle = '#f87171';
        ctx.setLineDash([3, 3]);
        ctx.moveTo(padding.left, y);
        ctx.lineTo(width - padding.right, y);
        ctx.stroke();
    }
    if (state.limits.max >= phMin && state.limits.max <= phMax) {
        const y = mapY(state.limits.max);
        ctx.beginPath();
        ctx.strokeStyle = '#60a5fa';
        ctx.setLineDash([3, 3]);
        ctx.moveTo(padding.left, y);
        ctx.lineTo(width - padding.right, y);
        ctx.stroke();
    }
    ctx.setLineDash([]);

    // Draw Line and Area Gradient
    if (state.chartData.length > 0) {
        const grad = ctx.createLinearGradient(0, padding.top, 0, padding.top + chartH);
        grad.addColorStop(0, 'rgba(74, 222, 128, 0.25)');
        grad.addColorStop(1, 'rgba(74, 222, 128, 0.02)');
        
        ctx.beginPath();
        ctx.moveTo(mapX(0), mapY(phValues[0]));
        for(let i=1; i<state.chartData.length; i++) {
            ctx.lineTo(mapX(i), mapY(phValues[i]));
        }
        ctx.lineTo(mapX(state.chartData.length-1), padding.top + chartH);
        ctx.lineTo(mapX(0), padding.top + chartH);
        ctx.fillStyle = grad;
        ctx.fill();
        
        // Lines
        for(let i=1; i<state.chartData.length; i++) {
            const p1 = phValues[i-1];
            const p2 = phValues[i];
            
            ctx.beginPath();
            ctx.lineWidth = 2;
            ctx.strokeStyle = phColor((p1 + p2) / 2);
            ctx.moveTo(mapX(i-1), mapY(p1));
            ctx.lineTo(mapX(i), mapY(p2));
            ctx.stroke();
        }
        
        // Dot at current value
        const lastVal = phValues[phValues.length - 1];
        ctx.beginPath();
        ctx.fillStyle = phColor(lastVal);
        ctx.arc(mapX(state.chartData.length - 1), mapY(lastVal), 4, 0, Math.PI*2);
        ctx.fill();
    }
}

// Fetch Status
let lastAlarmState = null;

async function fetchStatus() {
    try {
        const res = await fetch('/api/status');
        if (res.status === 401) return;
        if (!res.ok) throw new Error('Status fetch failed');
        const data = await res.json();
        
        const now = new Date();
        el.lastUpdate.textContent = data.ntpSynced && data.ntpTime ? data.ntpTime : now.toLocaleTimeString();
        el.statusDot.className = 'dot connected pulse';
        el.statusText.textContent = data.wifiRSSI ? `WiFi (${data.wifiRSSI} dBm)` : 'Połączono';
        if(data.firmwareVersion) el.fwVersion.textContent = 'v' + data.firmwareVersion;
        if(data.ip) document.getElementById('sys-ip').textContent = data.ip;
        
        // pH Card
        const valPh = document.getElementById('val-ph');
        valPh.textContent = data.ph !== undefined ? data.ph.toFixed(2) : '--.--';
        setPhColor(valPh, data.ph || 7.0);
        
        if (data.minPH !== undefined && data.maxPH !== undefined) {
            document.getElementById('val-ph-min').textContent = data.minPH.toFixed(2);
            document.getElementById('val-ph-max').textContent = data.maxPH.toFixed(2);
        }
        
        // Voltage
        if (data.voltage !== undefined) {
            document.getElementById('val-voltage').textContent = data.voltage.toFixed(3) + ' V';
        }
        
        // Temp
        if (data.temperature !== null && data.temperature !== undefined && data.temperature > -50) {
            document.getElementById('val-temp').textContent = data.temperature.toFixed(1) + ' °C';
            if (data.minTemp !== undefined && data.minTemp > -50) {
                document.getElementById('val-temp-min').textContent = data.minTemp.toFixed(1);
                document.getElementById('val-temp-max').textContent = data.maxTemp.toFixed(1);
            }
        } else {
            document.getElementById('val-temp').textContent = 'Brak czujnika';
        }
        
        // Alarm
        const alarmBadge = document.getElementById('val-alarm');
        const isAlarm = (data.alarmState > 0);
        if (isAlarm) {
            alarmBadge.textContent = data.alarmState === 1 ? 'ALARM (NISKI)' : 'ALARM (WYSOKI)';
            alarmBadge.className = 'card-value status-badge badge-alarm';
            if(lastAlarmState === false) {
                if(Notification.permission === 'granted') {
                    new Notification('pH Monitor - ALARM!', { body: `pH przekroczyło limit: ${data.ph.toFixed(2)}` });
                }
            }
        } else {
            alarmBadge.textContent = 'OK (W NORMIE)';
            alarmBadge.className = 'card-value status-badge badge-ok';
        }
        lastAlarmState = isAlarm;
        
        // Uptime & RSSI
        document.getElementById('val-uptime').textContent = formatTime(data.uptime || 0);
        document.getElementById('val-rssi').textContent = data.wifiRSSI || '--';
        
        // Live calibration readout & parameters
        document.getElementById('cal-live-v').textContent = (data.voltage || 0).toFixed(3) + ' V';
        document.getElementById('cal-live-ph').textContent = (data.ph || 7.0).toFixed(2) + ' pH';
        
        if (data.voltagePH7 !== undefined) {
            document.getElementById('cal-v7').textContent = (data.voltagePH7 / 1000).toFixed(3) + ' V';
        }
        if (data.voltagePH4 !== undefined) {
            document.getElementById('cal-v4').textContent = (data.voltagePH4 / 1000).toFixed(3) + ' V';
        }
        if (data.voltagePH9 !== undefined) {
            document.getElementById('cal-v9').textContent = (data.voltagePH9 / 1000).toFixed(3) + ' V';
        }
        
        if (data.calibration) {
            const b7 = document.getElementById('cal-badge-7');
            if (b7) {
                b7.textContent = data.calibration.ph7 ? '(skalibrowany)' : '(domyślny)';
                b7.style.color = data.calibration.ph7 ? '#4ade80' : '#718096';
            }
            const b4 = document.getElementById('cal-badge-4');
            if (b4) {
                b4.textContent = data.calibration.ph4 ? '(skalibrowany)' : '(domyślny)';
                b4.style.color = data.calibration.ph4 ? '#4ade80' : '#718096';
            }
            const b9 = document.getElementById('cal-badge-9');
            if (b9) {
                b9.textContent = data.calibration.ph9 ? '(skalibrowany)' : '(domyślny)';
                b9.style.color = data.calibration.ph9 ? '#4ade80' : '#718096';
            }
            const bComp = document.getElementById('cal-complete-badge');
            if (bComp) {
                bComp.textContent = data.calibration.complete ? 'Pełna (3-punktowa)' : 'Częściowa / Domyślna';
                bComp.style.color = data.calibration.complete ? '#4ade80' : '#facc15';
            }
        }
        
        // Electrode health estimation
        if (data.voltagePH4 && data.voltagePH7 && data.voltagePH9) {
            const slopeAcid = (data.voltagePH4 - data.voltagePH7) / 2.99; // mV per pH unit (ideal ~59.16 mV)
            const slopeBase = (data.voltagePH7 - data.voltagePH9) / 2.18; // mV per pH unit
            const avgSlope = (slopeAcid + slopeBase) / 2.0;
            const healthPct = Math.min(100, Math.max(0, Math.round((avgSlope / 59.16) * 100)));
            const healthEl = document.getElementById('cal-health');
            if (healthEl) {
                healthEl.textContent = healthPct + '%';
                healthEl.style.color = healthPct > 80 ? '#4ade80' : (healthPct > 60 ? '#facc15' : '#f87171');
            }
        }
        
        // Live chart append if empty
        if (!state.chartData || state.chartData.length === 0) {
            state.chartData = [{ t: Math.floor(Date.now()/1000), p: data.ph }];
            drawChart();
        }
        
    } catch (err) {
        console.error(err);
        el.statusDot.className = 'dot disconnected';
        el.statusText.textContent = 'Brak połączenia';
    }
}

// Fetch Config
async function fetchConfig() {
    try {
        const res = await fetch('/api/config');
        if (!res.ok) return;
        const data = await res.json();
        
        document.getElementById('cfg-devname').value = data.deviceName || '';
        document.getElementById('cfg-ph-min').value = data.alarmLow !== undefined ? data.alarmLow : 6.0;
        document.getElementById('cfg-ph-max').value = data.alarmHigh !== undefined ? data.alarmHigh : 8.0;
        document.getElementById('cfg-hysteresis').value = data.hysteresis !== undefined ? data.hysteresis : 0.1;
        document.getElementById('cfg-alarm-hold').value = data.alarmHoldSec !== undefined ? data.alarmHoldSec : 15;
        
        document.getElementById('cfg-push-en').checked = !!data.pushoverEnabled;
        if (data.pushoverConfigured) {
            document.getElementById('cfg-push-user').placeholder = 'Skonfigurowano (wpisz nowy)';
            document.getElementById('cfg-push-token').placeholder = 'Skonfigurowano (wpisz nowy)';
        }
        
        document.getElementById('cfg-mqtt-en').checked = !!data.mqttEnabled;
        document.getElementById('cfg-mqtt-broker').value = data.mqttBroker || '';
        document.getElementById('cfg-mqtt-port').value = data.mqttPort || 1883;
        document.getElementById('cfg-mqtt-user').value = data.mqttUser || '';

        document.getElementById('admin-user').value = data.adminUser || 'admin';
        
        state.limits.min = data.alarmLow !== undefined ? data.alarmLow : 6.0;
        state.limits.max = data.alarmHigh !== undefined ? data.alarmHigh : 8.0;
        document.getElementById('val-alarm-lim').textContent = `${state.limits.min.toFixed(1)} / ${state.limits.max.toFixed(1)}`;
        
    } catch(err) {
        console.error('Błąd pobierania konfiguracji', err);
    }
}

// Fetch History
async function fetchHistory() {
    try {
        const res = await fetch('/api/history?limit=120');
        if(!res.ok) return;
        const data = await res.json();
        if (Array.isArray(data) && data.length > 0) {
            state.chartData = data;
            drawChart();
        }
    } catch(err) {
        console.error('Błąd pobierania historii', err);
    }
}

// Save config
document.getElementById('settings-form').addEventListener('submit', async (e) => {
    e.preventDefault();
    const btn = document.getElementById('btn-save-cfg');
    const status = document.getElementById('cfg-save-status');
    btn.disabled = true;
    
    const payload = {
        deviceName: document.getElementById('cfg-devname').value,
        alarmLow: parseFloat(document.getElementById('cfg-ph-min').value),
        alarmHigh: parseFloat(document.getElementById('cfg-ph-max').value),
        hysteresis: parseFloat(document.getElementById('cfg-hysteresis').value),
        alarmHoldSec: parseInt(document.getElementById('cfg-alarm-hold').value),
        pushoverEnabled: document.getElementById('cfg-push-en').checked,
        mqttEnabled: document.getElementById('cfg-mqtt-en').checked,
        mqttBroker: document.getElementById('cfg-mqtt-broker').value,
        mqttPort: parseInt(document.getElementById('cfg-mqtt-port').value),
        mqttUser: document.getElementById('cfg-mqtt-user').value
    };
    
    const pushUser = document.getElementById('cfg-push-user').value.trim();
    const pushToken = document.getElementById('cfg-push-token').value.trim();
    const mqttPass = document.getElementById('cfg-mqtt-pass').value.trim();
    
    if (pushUser.length > 0) payload.pushoverUser = pushUser;
    if (pushToken.length > 0) payload.pushoverToken = pushToken;
    if (mqttPass.length > 0) payload.mqttPass = mqttPass;

    try {
        const res = await fetch('/api/config', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(payload)
        });
        if(res.ok) {
            status.textContent = 'Zapisano pomyślnie!';
            status.style.color = '#4ade80';
            setTimeout(() => status.textContent = '', 3000);
            fetchConfig();
        } else {
            const errJson = await res.json().catch(() => ({}));
            status.textContent = errJson.error || 'Błąd zapisu';
            status.style.color = '#f87171';
        }
    } catch(err) {
        status.textContent = 'Błąd sieci';
        status.style.color = '#f87171';
    } finally {
        btn.disabled = false;
    }
});

// Admin form
document.getElementById('admin-form').addEventListener('submit', async (e) => {
    e.preventDefault();
    const btn = document.getElementById('btn-save-admin');
    const status = document.getElementById('admin-save-status');
    btn.disabled = true;
    
    const payload = {
        adminUser: document.getElementById('admin-user').value.trim()
    };
    const pass = document.getElementById('admin-pass').value.trim();
    if (pass.length > 0) payload.adminPass = pass;
    
    try {
        const res = await fetch('/api/config', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(payload)
        });
        if(res.ok) {
            status.textContent = 'Zapisano! Przeładuj stronę, aby zalogować się nowymi danymi.';
            status.style.color = '#4ade80';
        } else {
            const errJson = await res.json().catch(() => ({}));
            status.textContent = errJson.error || 'Błąd zapisu';
            status.style.color = '#f87171';
        }
    } catch(err) {
        status.textContent = 'Błąd połączenia';
        status.style.color = '#f87171';
    } finally {
        btn.disabled = false;
    }
});

// Test Pushover
document.getElementById('btn-test-push').addEventListener('click', async () => {
    const btn = document.getElementById('btn-test-push');
    btn.disabled = true;
    const oldText = btn.textContent;
    btn.textContent = 'Wysyłanie...';
    try {
        const res = await fetch('/api/pushover/test', { method: 'POST' });
        if (res.ok) {
            btn.textContent = 'Wysłano pomyślnie!';
        } else {
            const err = await res.json().catch(() => ({}));
            btn.textContent = err.message || 'Błąd wysyłania';
        }
        setTimeout(() => { btn.textContent = oldText; btn.disabled = false; }, 3000);
    } catch(err) {
        btn.textContent = 'Błąd połączenia';
        setTimeout(() => { btn.textContent = oldText; btn.disabled = false; }, 3000);
    }
});

// Reset Stats
document.getElementById('btn-reset-stats').addEventListener('click', async () => {
    if(confirm('Na pewno zresetować wartości Min/Max?')) {
        await fetch('/api/reset-stats', { method: 'POST' });
        fetchStatus();
    }
});

// Download CSV
document.getElementById('btn-dl-csv').addEventListener('click', () => {
    if(!state.chartData || state.chartData.length === 0) return;
    const csvRows = ['timestamp,ph,temperature,voltage,alarmState'];
    state.chartData.forEach(row => {
        const t = row.t || row.timestamp || '';
        const p = (row.p !== undefined ? row.p : row.ph) || 0;
        const te = (row.te !== undefined ? row.te : row.temperature) || '';
        const v = (row.v !== undefined ? row.v : row.voltage) || '';
        const a = (row.a !== undefined ? row.a : row.alarmState) || 0;
        csvRows.push(`${t},${p},${te},${v},${a}`);
    });
    const blob = new Blob([csvRows.join('\n')], { type: 'text/csv;charset=utf-8;' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `ph_monitor_history_${new Date().toISOString().slice(0,10)}.csv`;
    a.click();
    window.URL.revokeObjectURL(url);
});

// Calibration
let calibPollInterval = null;

function setCalibButtonsDisabled(disabled) {
    document.querySelectorAll('.cal-btn').forEach(b => {
        b.disabled = disabled;
    });
}

async function calibrate(type, customVal = 0) {
    const statusBox = document.getElementById('calib-status-box');
    statusBox.style.display = 'block';
    statusBox.textContent = 'Inicjalizacja kalibracji...';
    statusBox.style.backgroundColor = 'rgba(59, 130, 246, 0.15)';
    statusBox.style.color = '#60a5fa';
    
    setCalibButtonsDisabled(true);
    
    let endpointType = type;
    if (type === '7.00') endpointType = 'neutral';
    else if (type === '4.01') endpointType = 'acid';
    else if (type === '9.18') endpointType = 'base';
    
    try {
        const res = await fetch('/api/calibrate', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ type: endpointType, customPH: customVal })
        });
        
        if (res.status === 401) {
            setCalibButtonsDisabled(false);
            statusBox.textContent = 'Wymagane logowanie administratora (Basic Auth)';
            statusBox.style.backgroundColor = 'rgba(239, 68, 68, 0.2)';
            statusBox.style.color = '#f87171';
            return;
        }
        
        if (!res.ok) {
            const errData = await res.json().catch(() => ({}));
            throw new Error(errData.message || 'Błąd rozpoczęcia kalibracji');
        }
        
        if (type === 'reset') {
            statusBox.textContent = 'Kalibracja zresetowana do wartości fabrycznych!';
            statusBox.style.backgroundColor = 'rgba(74, 222, 128, 0.2)';
            statusBox.style.color = '#4ade80';
            setCalibButtonsDisabled(false);
            fetchStatus();
            return;
        }
        
        statusBox.textContent = 'Zbieranie i analiza stabilności próbek (5s)...';
        
        if (calibPollInterval) clearInterval(calibPollInterval);
        calibPollInterval = setInterval(pollCalibration, 500);
        
    } catch(err) {
        setCalibButtonsDisabled(false);
        statusBox.textContent = 'Błąd: ' + err.message;
        statusBox.style.backgroundColor = 'rgba(239, 68, 68, 0.2)';
        statusBox.style.color = '#f87171';
    }
}

function calibrateCustom() {
    const val = parseFloat(document.getElementById('cal-custom-val').value);
    if(isNaN(val) || val < 0 || val > 14) {
        alert('Podaj prawidłową wartość pH bufora (0-14)');
        return;
    }
    calibrate('custom', val);
}

async function pollCalibration() {
    try {
        const res = await fetch('/api/calibrate/status');
        const data = await res.json();
        const statusBox = document.getElementById('calib-status-box');
        
        if (data.status === 'collecting') {
            const prog = data.progress !== undefined ? ` (${data.progress}%)` : '';
            statusBox.textContent = (data.message || 'Trwa badanie stabilności sygnału...') + prog;
            statusBox.style.backgroundColor = 'rgba(59, 130, 246, 0.15)';
            statusBox.style.color = '#60a5fa';
        } else if (data.status === 'done') {
            clearInterval(calibPollInterval);
            setCalibButtonsDisabled(false);
            statusBox.textContent = `${data.message || 'Kalibracja zakończona pomyślnie!'} (Napięcie: ${(data.voltage/1000).toFixed(3)} V, stdDev: ${(data.stdDev||0).toFixed(2)} mV)`;
            statusBox.style.backgroundColor = 'rgba(74, 222, 128, 0.2)';
            statusBox.style.color = '#4ade80';
            fetchStatus();
        } else if (data.status === 'failed') {
            clearInterval(calibPollInterval);
            setCalibButtonsDisabled(false);
            statusBox.textContent = 'Błąd kalibracji: ' + (data.message || data.error || 'Pomiar niestabilny');
            statusBox.style.backgroundColor = 'rgba(239, 68, 68, 0.2)';
            statusBox.style.color = '#f87171';
        }
    } catch(err) {
        console.error(err);
    }
}

// Request Notification Permission
if ("Notification" in window && Notification.permission !== "granted" && Notification.permission !== "denied") {
    Notification.requestPermission();
}

// Initialization and Loops
window.addEventListener('resize', drawChart);
fetchConfig().then(() => {
    fetchHistory();
    fetchStatus();
    setInterval(fetchStatus, 2000);
    setInterval(fetchHistory, 60000);
});

)rawliteral";


const char STYLE_CSS[] PROGMEM = R"rawliteral(
:root {
    --bg-main: #f3f4f6;
    --bg-card: #ffffff;
    --border-card: #e5e7eb;
    --text-primary: #111827;
    --text-muted: #6b7280;
    --color-acid: #ef4444;
    --color-neutral: #22c55e;
    --color-base: #3b82f6;
    --color-alarm: #f97316;
    --bg-input: #f9fafb;
    --border-input: #d1d5db;
    --focus-ring: #3b82f6;
    --color-btn-primary: #2563eb;
    --color-btn-primary-hover: #1d4ed8;
    --color-btn-secondary: #4b5563;
    --color-btn-secondary-hover: #374151;
    --color-btn-danger: #ef4444;
    --color-btn-danger-hover: #dc2626;
    --color-btn-warning: #f59e0b;
    --color-btn-warning-hover: #d97706;
}

[data-theme="dark"] {
    --bg-main: #0b0e18;
    --bg-card: #131726;
    --border-card: #1e2235;
    --text-primary: #dde1ef;
    --text-muted: #4a5070;
    --color-acid: #f87171;
    --color-neutral: #4ade80;
    --color-base: #60a5fa;
    --color-alarm: #fb923c;
    --bg-input: #0b0e18;
    --border-input: #2a2e45;
    --focus-ring: #3b82f6;
    --color-btn-primary: #3b82f6;
    --color-btn-primary-hover: #2563eb;
    --color-btn-secondary: #374151;
    --color-btn-secondary-hover: #4b5563;
    --color-btn-danger: #ef4444;
    --color-btn-danger-hover: #dc2626;
    --color-btn-warning: #f59e0b;
    --color-btn-warning-hover: #d97706;
}

* {
    box-sizing: border-box;
    margin: 0;
    padding: 0;
}

body {
    font-family: 'Inter', system-ui, -apple-system, sans-serif;
    background-color: var(--bg-main);
    color: var(--text-primary);
    line-height: 1.5;
    transition: background-color 0.3s, color 0.3s;
}

.container {
    max-width: 1200px;
    margin: 0 auto;
    padding: 20px;
}

header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 24px;
    padding-bottom: 16px;
    border-bottom: 1px solid var(--border-card);
}

.header-left h1 {
    font-size: 24px;
    margin-bottom: 4px;
    display: flex;
    align-items: center;
    gap: 12px;
}

.badge {
    font-size: 12px;
    padding: 2px 8px;
    background: var(--bg-card);
    border: 1px solid var(--border-card);
    border-radius: 12px;
    color: var(--text-muted);
}

.status-indicator {
    display: flex;
    align-items: center;
    gap: 8px;
    font-size: 14px;
    color: var(--text-muted);
}

.dot {
    width: 10px;
    height: 10px;
    border-radius: 50%;
    background-color: var(--text-muted);
}

.dot.connected {
    background-color: var(--color-neutral);
}

.dot.disconnected {
    background-color: var(--color-acid);
}

.pulse {
    animation: pulse 2s infinite;
}

@keyframes pulse {
    0% { box-shadow: 0 0 0 0 rgba(74, 222, 128, 0.4); }
    70% { box-shadow: 0 0 0 6px rgba(74, 222, 128, 0); }
    100% { box-shadow: 0 0 0 0 rgba(74, 222, 128, 0); }
}

.cards-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
    gap: 16px;
    margin-bottom: 24px;
}

.card {
    background-color: var(--bg-card);
    border: 1px solid var(--border-card);
    border-radius: 14px;
    padding: 20px;
    box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06);
}

.card-title {
    font-size: 14px;
    color: var(--text-muted);
    font-weight: 500;
    margin-bottom: 8px;
}

.card-value {
    font-size: 32px;
    font-weight: 700;
    margin-bottom: 8px;
}

.text-medium {
    font-size: 24px;
}

.ph-value {
    color: var(--color-neutral);
}

.card-stats {
    font-size: 12px;
    color: var(--text-muted);
}

.status-badge {
    display: inline-block;
    font-size: 20px;
    padding: 4px 12px;
    border-radius: 8px;
    font-weight: 600;
}

.badge-ok {
    background-color: rgba(74, 222, 128, 0.2);
    color: var(--color-neutral);
}

.badge-alarm {
    background-color: rgba(239, 68, 68, 0.2);
    color: var(--color-acid);
    animation: blink 1s infinite;
}

@keyframes blink {
    50% { opacity: 0.5; }
}

.chart-section {
    margin-bottom: 24px;
}

.card-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 16px;
}

.card-header h2 {
    font-size: 18px;
    font-weight: 600;
}

.chart-container {
    width: 100%;
    height: 300px;
    position: relative;
}

.two-col-grid {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 24px;
    margin-bottom: 24px;
}

@media (max-width: 900px) {
    .two-col-grid {
        grid-template-columns: 1fr;
    }
}

.settings-grid {
    display: grid;
    grid-template-columns: 1fr 1fr 1fr;
    gap: 20px;
    margin-bottom: 20px;
}

@media (max-width: 1024px) {
    .settings-grid {
        grid-template-columns: 1fr;
    }
}

.settings-col h3, .calib-info h3, .calib-actions h3 {
    font-size: 14px;
    color: var(--text-muted);
    margin-bottom: 12px;
    padding-bottom: 8px;
    border-bottom: 1px solid var(--border-card);
}

.form-group {
    margin-bottom: 12px;
}

.form-group label {
    display: block;
    font-size: 13px;
    margin-bottom: 4px;
    color: var(--text-muted);
}

.form-group input[type="text"],
.form-group input[type="number"],
.form-group input[type="password"] {
    width: 100%;
    padding: 8px 12px;
    background-color: var(--bg-input);
    border: 1px solid var(--border-input);
    border-radius: 6px;
    color: var(--text-primary);
    font-family: inherit;
    font-size: 14px;
}

.form-group input:focus {
    outline: none;
    border-color: var(--focus-ring);
    box-shadow: 0 0 0 2px rgba(59, 130, 246, 0.2);
}

.checkbox {
    display: flex;
    align-items: center;
    gap: 8px;
}

.checkbox label {
    margin-bottom: 0;
}

.btn {
    padding: 8px 16px;
    border: none;
    border-radius: 6px;
    font-size: 14px;
    font-weight: 500;
    cursor: pointer;
    transition: background-color 0.2s;
    color: white;
}

.btn-icon {
    padding: 8px;
    background: transparent;
    color: var(--text-primary);
}

.btn-icon:hover {
    background: var(--border-card);
}

.btn-primary { background-color: var(--color-btn-primary); }
.btn-primary:hover { background-color: var(--color-btn-primary-hover); }

.btn-secondary { background-color: var(--color-btn-secondary); }
.btn-secondary:hover { background-color: var(--color-btn-secondary-hover); }

.btn-danger { background-color: var(--color-btn-danger); }
.btn-danger:hover { background-color: var(--color-btn-danger-hover); }

.btn-warning { background-color: var(--color-btn-warning); }
.btn-warning:hover { background-color: var(--color-btn-warning-hover); }

.form-actions {
    display: flex;
    align-items: center;
    gap: 16px;
    margin-top: 20px;
    padding-top: 16px;
    border-top: 1px solid var(--border-card);
}

.status-msg {
    font-size: 14px;
    color: var(--color-neutral);
}

.calib-grid {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 20px;
}

@media (max-width: 600px) {
    .calib-grid {
        grid-template-columns: 1fr;
    }
}

.param-list {
    list-style: none;
    margin-bottom: 16px;
}

.param-list li {
    display: flex;
    justify-content: space-between;
    padding: 6px 0;
    border-bottom: 1px dashed var(--border-card);
    font-size: 14px;
}

.live-reading {
    background-color: rgba(96, 165, 250, 0.1);
    border: 1px solid rgba(96, 165, 250, 0.2);
    padding: 12px;
    border-radius: 8px;
    text-align: center;
    font-size: 14px;
}

.btn-group-grid {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 8px;
}

.custom-calib {
    display: flex;
    gap: 8px;
}

.custom-calib input {
    width: 100%;
    padding: 8px 12px;
    background-color: var(--bg-input);
    border: 1px solid var(--border-input);
    border-radius: 6px;
    color: var(--text-primary);
}

.cal-badge {
    font-size: 11px;
    margin-left: 6px;
}

.cal-btn:disabled {
    opacity: 0.5;
    cursor: not-allowed;
}

.calib-status {
    margin-top: 16px;
    padding: 12px;
    background-color: var(--border-card);
    border-radius: 8px;
    text-align: center;
    font-size: 14px;
    font-weight: 500;
}

.admin-section {
    margin-bottom: 24px;
}

.form-group-inline {
    display: flex;
    align-items: flex-end;
    gap: 16px;
    flex-wrap: wrap;
}

.form-group-inline .form-group {
    margin-bottom: 0;
    min-width: 200px;
}

footer {
    padding-top: 24px;
    border-top: 1px solid var(--border-card);
    color: var(--text-muted);
    font-size: 13px;
    padding-bottom: 24px;
}

.footer-content {
    display: flex;
    justify-content: space-between;
    align-items: center;
    flex-wrap: wrap;
    gap: 12px;
}

.links a {
    color: var(--color-base);
    text-decoration: none;
}

.links a:hover {
    text-decoration: underline;
}

)rawliteral";


const char INDEX_HTML[] PROGMEM = R"rawliteral(
<!DOCTYPE html>
<html lang="pl" data-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>pH Monitor</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="style.css?v=3">
</head>
<body>
    <div class="container">
        <header>
            <div class="header-left">
                <h1>pH Monitor <span id="fw-version" class="badge">v1.0.0</span></h1>
                <div class="status-indicator">
                    <span id="status-dot" class="dot pulse"></span>
                    <span id="status-text">Oczekiwanie na dane...</span>
                    <span class="last-update">(Aktualizacja: <span id="last-update">--:--:--</span>)</span>
                </div>
            </div>
            <div class="header-right">
                <button id="theme-toggle" class="btn btn-icon" title="Przełącz motyw">
                    <svg id="theme-icon-light" style="display: none;" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="5"></circle><line x1="12" y1="1" x2="12" y2="3"></line><line x1="12" y1="21" x2="12" y2="23"></line><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"></line><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"></line><line x1="1" y1="12" x2="3" y2="12"></line><line x1="21" y1="12" x2="23" y2="12"></line><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"></line><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"></line></svg>
                    <svg id="theme-icon-dark" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"></path></svg>
                </button>
            </div>
        </header>

        <main>
            <section class="cards-grid">
                <div class="card val-card" id="card-ph">
                    <div class="card-title">pH Zmierzone</div>
                    <div class="card-value ph-value" id="val-ph">--.--</div>
                    <div class="card-stats">Min: <span id="val-ph-min">--.--</span> | Max: <span id="val-ph-max">--.--</span></div>
                </div>
                
                <div class="card val-card">
                    <div class="card-title">Napięcie Sondy (V)</div>
                    <div class="card-value" id="val-voltage">-.---</div>
                    <div class="card-stats">Raw ADC</div>
                </div>

                <div class="card val-card">
                    <div class="card-title">Temperatura (°C)</div>
                    <div class="card-value" id="val-temp">--.-</div>
                    <div class="card-stats">Min: <span id="val-temp-min">--.-</span> | Max: <span id="val-temp-max">--.-</span></div>
                </div>

                <div class="card val-card">
                    <div class="card-title">Status Alarmu</div>
                    <div class="card-value status-badge badge-ok" id="val-alarm">OK</div>
                    <div class="card-stats">Limity: <span id="val-alarm-lim">-- / --</span></div>
                </div>

                <div class="card val-card">
                    <div class="card-title">Czas Pracy (Uptime)</div>
                    <div class="card-value text-medium" id="val-uptime">--:--:--</div>
                    <div class="card-stats">WIFI: <span id="val-rssi">--</span> dBm</div>
                </div>
            </section>

            <section class="chart-section card">
                <div class="card-header">
                    <h2>Historia pH</h2>
                    <div class="actions">
                        <button id="btn-reset-stats" class="btn btn-secondary">Reset Min/Max</button>
                        <button id="btn-dl-csv" class="btn btn-secondary">Pobierz CSV</button>
                    </div>
                </div>
                <div class="chart-container">
                    <canvas id="phChart"></canvas>
                </div>
            </section>

            <div class="two-col-grid">
                <section class="settings-section card">
                    <div class="card-header">
                        <h2>Ustawienia</h2>
                    </div>
                    <form id="settings-form">
                        <div class="settings-grid">
                            <div class="settings-col">
                                <h3>Podstawowe</h3>
                                <div class="form-group">
                                    <label for="cfg-devname">Nazwa urządzenia</label>
                                    <input type="text" id="cfg-devname" name="devname" required>
                                </div>
                                <div class="form-group">
                                    <label for="cfg-ph-min">Alarm Low (pH)</label>
                                    <input type="number" step="0.01" id="cfg-ph-min" name="ph_min" required>
                                </div>
                                <div class="form-group">
                                    <label for="cfg-ph-max">Alarm High (pH)</label>
                                    <input type="number" step="0.01" id="cfg-ph-max" name="ph_max" required>
                                </div>
                                <div class="form-group">
                                    <label for="cfg-hysteresis">Histereza (pH)</label>
                                    <input type="number" step="0.01" id="cfg-hysteresis" name="hysteresis" required>
                                </div>
                                <div class="form-group">
                                    <label for="cfg-alarm-hold">Opóźnienie alarmu (s)</label>
                                    <input type="number" id="cfg-alarm-hold" name="alarm_hold" required>
                                </div>
                            </div>
                            
                            <div class="settings-col">
                                <h3>Powiadomienia Pushover</h3>
                                <div class="form-group checkbox">
                                    <input type="checkbox" id="cfg-push-en" name="push_en">
                                    <label for="cfg-push-en">Włącz Pushover</label>
                                </div>
                                <div class="form-group">
                                    <label for="cfg-push-user">Klucz Użytkownika</label>
                                    <input type="password" id="cfg-push-user" name="push_user" placeholder="Wpisz aby zmienić">
                                </div>
                                <div class="form-group">
                                    <label for="cfg-push-token">Token Aplikacji</label>
                                    <input type="password" id="cfg-push-token" name="push_token" placeholder="Wpisz aby zmienić">
                                </div>
                                <div class="form-group">
                                    <button type="button" id="btn-test-push" class="btn btn-secondary">Testuj Powiadomienie</button>
                                </div>
                            </div>

                            <div class="settings-col">
                                <h3>MQTT</h3>
                                <div class="form-group checkbox">
                                    <input type="checkbox" id="cfg-mqtt-en" name="mqtt_en">
                                    <label for="cfg-mqtt-en">Włącz MQTT</label>
                                </div>
                                <div class="form-group">
                                    <label for="cfg-mqtt-broker">Broker (IP/Domena)</label>
                                    <input type="text" id="cfg-mqtt-broker" name="mqtt_broker">
                                </div>
                                <div class="form-group">
                                    <label for="cfg-mqtt-port">Port</label>
                                    <input type="number" id="cfg-mqtt-port" name="mqtt_port">
                                </div>
                                <div class="form-group">
                                    <label for="cfg-mqtt-user">Użytkownik</label>
                                    <input type="text" id="cfg-mqtt-user" name="mqtt_user">
                                </div>
                                <div class="form-group">
                                    <label for="cfg-mqtt-pass">Hasło</label>
                                    <input type="password" id="cfg-mqtt-pass" name="mqtt_pass" placeholder="Wpisz aby zmienić">
                                </div>
                            </div>
                        </div>
                        <div class="form-actions">
                            <button type="submit" class="btn btn-primary" id="btn-save-cfg">Zapisz Ustawienia</button>
                            <span id="cfg-save-status" class="status-msg"></span>
                        </div>
                    </form>
                </section>

                <section class="calib-section card">
                    <div class="card-header">
                        <h2>Kalibracja Sondy</h2>
                    </div>
                    <div class="calib-grid">
                        <div class="calib-info">
                            <h3>Parametry</h3>
                            <ul class="param-list">
                                <li><span>pH 7.00:</span> <strong id="cal-v7">-.--- V</strong> <small id="cal-badge-7" class="cal-badge">(domyślny)</small></li>
                                <li><span>pH 4.01:</span> <strong id="cal-v4">-.--- V</strong> <small id="cal-badge-4" class="cal-badge">(domyślny)</small></li>
                                <li><span>pH 9.18:</span> <strong id="cal-v9">-.--- V</strong> <small id="cal-badge-9" class="cal-badge">(domyślny)</small></li>
                                <li><span>Status:</span> <strong id="cal-complete-badge">Niekompletna</strong></li>
                                <li><span>Kondycja:</span> <strong id="cal-health">--%</strong></li>
                            </ul>
                            <div class="live-reading">
                                Obecnie: <strong id="cal-live-v">-.--- V</strong> / <strong id="cal-live-ph">--.-- pH</strong>
                            </div>
                        </div>
                        
                        <div class="calib-actions">
                            <h3>Bufory Standardowe</h3>
                            <div class="btn-group-grid">
                                <button type="button" class="btn btn-secondary cal-btn" id="btn-cal-7" onclick="calibrate('7.00')">Kalibruj pH 7.00</button>
                                <button type="button" class="btn btn-secondary cal-btn" id="btn-cal-4" onclick="calibrate('4.01')">Kalibruj pH 4.01</button>
                                <button type="button" class="btn btn-secondary cal-btn" id="btn-cal-9" onclick="calibrate('9.18')">Kalibruj pH 9.18</button>
                                <button type="button" class="btn btn-danger cal-btn" id="btn-cal-reset" onclick="calibrate('reset')">Reset Do Fabrycznych</button>
                            </div>
                            
                            <h3 style="margin-top: 15px;">Własny Bufor</h3>
                            <div class="custom-calib">
                                <input type="number" step="0.01" id="cal-custom-val" placeholder="np. 6.86">
                                <button type="button" class="btn btn-secondary cal-btn" id="btn-cal-custom" onclick="calibrateCustom()">Kalibruj</button>
                            </div>
                        </div>
                    </div>
                    <div id="calib-status-box" class="calib-status" style="display: none; margin-top: 15px; padding: 12px; border-radius: 8px; font-weight: 500;">
                        --
                    </div>
                </section>
            </div>
            
            <section class="admin-section card">
                <div class="card-header">
                    <h2>Bezpieczeństwo</h2>
                </div>
                <form id="admin-form">
                    <div class="form-group-inline">
                        <div class="form-group">
                            <label for="admin-user">Admin Użytkownik</label>
                            <input type="text" id="admin-user" name="admin_user">
                        </div>
                        <div class="form-group">
                            <label for="admin-pass">Admin Hasło</label>
                            <input type="password" id="admin-pass" name="admin_pass" placeholder="Wpisz aby zmienić">
                        </div>
                        <button type="submit" class="btn btn-warning" id="btn-save-admin">Zmień Dane Logowania</button>
                        <span id="admin-save-status" class="status-msg"></span>
                    </div>
                </form>
            </section>
        </main>

        <footer>
            <div class="footer-content">
                <div class="creator">Made by Wisnia</div>
                <div class="sys-info">IP: <span id="sys-ip">--.--.--.--</span> | Odświeżanie: 2s</div>
                <div class="links">
                    <a href="/api/status" target="_blank">API Status</a> | 
                    <a href="/update" target="_blank">Aktualizacja OTA</a>
                </div>
            </div>
        </footer>
    </div>
    <script src="app.js?v=3"></script>
</body>
</html>

)rawliteral";


